python:
  - 3.7
gsl:
  - 2.6
boost:
  - 1.71
openmpi:
  - 4.1.0
numpy:
  - 1.20.0
numpyext:
  - 0.1.3
bpext:
  - 0.1.4
histogram:
  - 0.3.9
drchops:
  - 2.0.3
pyre:
  - 0.8

pin_run_as_build:
  setuptools:
    max_pin: x.x
  boost:
    max_pin: x.x
  openmpi:
    max_pin: x.x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
  numpyext:
    max_pin: x.x
  bpext:
    max_pin: x.x
  histogram:
    max_pin: x.x
  drchops:
    max_pin: x.x
  pyre:
    max_pin: x.x
